#remote:
#  service-group: tony.tonyirl.account
#  service-name: account.api
#  service-port: ${remote.port:10086}
#
#mybatis:
#  type-aliases-package: me.tony.tonyirl.account.orm.domain
#  mapper-locations: classpath*:mappers/*Mapper.xml
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:6606/tonyirl_account
    username: tony
    password: zby4163979
    name: tonyirlAccountDataSource
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: me.tony.tonyirl.account.orm.domain






