#remote:
#  service-group: tony.tonyirl.account
#  service-name: account.api
#  service-port: ${remote.port:10086}
#
#mybatis:
#  type-aliases-package: me.tony.tonyirl.account.orm.domain
#  mapper-locations: classpath*:mappers/*Mapper.xml
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      filter:
        stat:
          slow-sql-millis: 500
          log-slow-sql: true
        slf4j:
          enabled: true
  profiles:
    active: @spring.profile.active@
  cloud:
    service-registry:
      auto-registration:
        enabled: true

    zookeeper:
      connect-string: localhost:2181
      discovery:
        uri-spec: {address}:{port}
        register: true
        prefer-ip-address: true
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: me.tony.tonyirl.account.orm.domain

thrift:
  providers:
    - service: me.tony






