spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      username: bootz
      password: 123456
    url: jdbc:postgresql://localhost:5432/bootz_account
  jackson:
    time-zone: GMT+8
  jpa:
    hibernate:
      ddl-auto: none
