/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package me.tony.tonyirl.account.api.dto;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)", date = "2017-07-05")
public class AccountPassword implements org.apache.thrift.TBase<AccountPassword, AccountPassword._Fields>, java.io.Serializable, Cloneable, Comparable<AccountPassword> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("AccountPassword");

  private static final org.apache.thrift.protocol.TField ID_FIELD_DESC = new org.apache.thrift.protocol.TField("id", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField ACCOUNT_PASSWORD_FIELD_DESC = new org.apache.thrift.protocol.TField("accountPassword", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField ENCRYPT_TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("encryptType", org.apache.thrift.protocol.TType.I32, (short)3);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new AccountPasswordStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new AccountPasswordTupleSchemeFactory();

  public long id; // required
  public java.lang.String accountPassword; // required
  /**
   * 
   * @see me.tony.tonyirl.account.api.enums.PasswordEncryptType
   */
  public me.tony.tonyirl.account.api.enums.PasswordEncryptType encryptType; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ID((short)1, "id"),
    ACCOUNT_PASSWORD((short)2, "accountPassword"),
    /**
     * 
     * @see me.tony.tonyirl.account.api.enums.PasswordEncryptType
     */
    ENCRYPT_TYPE((short)3, "encryptType");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ID
          return ID;
        case 2: // ACCOUNT_PASSWORD
          return ACCOUNT_PASSWORD;
        case 3: // ENCRYPT_TYPE
          return ENCRYPT_TYPE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __ID_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ID, new org.apache.thrift.meta_data.FieldMetaData("id", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.ACCOUNT_PASSWORD, new org.apache.thrift.meta_data.FieldMetaData("accountPassword", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.ENCRYPT_TYPE, new org.apache.thrift.meta_data.FieldMetaData("encryptType", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, me.tony.tonyirl.account.api.enums.PasswordEncryptType.class)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(AccountPassword.class, metaDataMap);
  }

  public AccountPassword() {
  }

  public AccountPassword(
    long id,
    java.lang.String accountPassword,
    me.tony.tonyirl.account.api.enums.PasswordEncryptType encryptType)
  {
    this();
    this.id = id;
    setIdIsSet(true);
    this.accountPassword = accountPassword;
    this.encryptType = encryptType;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public AccountPassword(AccountPassword other) {
    __isset_bitfield = other.__isset_bitfield;
    this.id = other.id;
    if (other.isSetAccountPassword()) {
      this.accountPassword = other.accountPassword;
    }
    if (other.isSetEncryptType()) {
      this.encryptType = other.encryptType;
    }
  }

  public AccountPassword deepCopy() {
    return new AccountPassword(this);
  }

  @Override
  public void clear() {
    setIdIsSet(false);
    this.id = 0;
    this.accountPassword = null;
    this.encryptType = null;
  }

  public long getId() {
    return this.id;
  }

  public AccountPassword setId(long id) {
    this.id = id;
    setIdIsSet(true);
    return this;
  }

  public void unsetId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ID_ISSET_ID);
  }

  /** Returns true if field id is set (has been assigned a value) and false otherwise */
  public boolean isSetId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ID_ISSET_ID);
  }

  public void setIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ID_ISSET_ID, value);
  }

  public java.lang.String getAccountPassword() {
    return this.accountPassword;
  }

  public AccountPassword setAccountPassword(java.lang.String accountPassword) {
    this.accountPassword = accountPassword;
    return this;
  }

  public void unsetAccountPassword() {
    this.accountPassword = null;
  }

  /** Returns true if field accountPassword is set (has been assigned a value) and false otherwise */
  public boolean isSetAccountPassword() {
    return this.accountPassword != null;
  }

  public void setAccountPasswordIsSet(boolean value) {
    if (!value) {
      this.accountPassword = null;
    }
  }

  /**
   * 
   * @see me.tony.tonyirl.account.api.enums.PasswordEncryptType
   */
  public me.tony.tonyirl.account.api.enums.PasswordEncryptType getEncryptType() {
    return this.encryptType;
  }

  /**
   * 
   * @see me.tony.tonyirl.account.api.enums.PasswordEncryptType
   */
  public AccountPassword setEncryptType(me.tony.tonyirl.account.api.enums.PasswordEncryptType encryptType) {
    this.encryptType = encryptType;
    return this;
  }

  public void unsetEncryptType() {
    this.encryptType = null;
  }

  /** Returns true if field encryptType is set (has been assigned a value) and false otherwise */
  public boolean isSetEncryptType() {
    return this.encryptType != null;
  }

  public void setEncryptTypeIsSet(boolean value) {
    if (!value) {
      this.encryptType = null;
    }
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case ID:
      if (value == null) {
        unsetId();
      } else {
        setId((java.lang.Long)value);
      }
      break;

    case ACCOUNT_PASSWORD:
      if (value == null) {
        unsetAccountPassword();
      } else {
        setAccountPassword((java.lang.String)value);
      }
      break;

    case ENCRYPT_TYPE:
      if (value == null) {
        unsetEncryptType();
      } else {
        setEncryptType((me.tony.tonyirl.account.api.enums.PasswordEncryptType)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case ID:
      return getId();

    case ACCOUNT_PASSWORD:
      return getAccountPassword();

    case ENCRYPT_TYPE:
      return getEncryptType();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case ID:
      return isSetId();
    case ACCOUNT_PASSWORD:
      return isSetAccountPassword();
    case ENCRYPT_TYPE:
      return isSetEncryptType();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof AccountPassword)
      return this.equals((AccountPassword)that);
    return false;
  }

  public boolean equals(AccountPassword that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_id = true;
    boolean that_present_id = true;
    if (this_present_id || that_present_id) {
      if (!(this_present_id && that_present_id))
        return false;
      if (this.id != that.id)
        return false;
    }

    boolean this_present_accountPassword = true && this.isSetAccountPassword();
    boolean that_present_accountPassword = true && that.isSetAccountPassword();
    if (this_present_accountPassword || that_present_accountPassword) {
      if (!(this_present_accountPassword && that_present_accountPassword))
        return false;
      if (!this.accountPassword.equals(that.accountPassword))
        return false;
    }

    boolean this_present_encryptType = true && this.isSetEncryptType();
    boolean that_present_encryptType = true && that.isSetEncryptType();
    if (this_present_encryptType || that_present_encryptType) {
      if (!(this_present_encryptType && that_present_encryptType))
        return false;
      if (!this.encryptType.equals(that.encryptType))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(id);

    hashCode = hashCode * 8191 + ((isSetAccountPassword()) ? 131071 : 524287);
    if (isSetAccountPassword())
      hashCode = hashCode * 8191 + accountPassword.hashCode();

    hashCode = hashCode * 8191 + ((isSetEncryptType()) ? 131071 : 524287);
    if (isSetEncryptType())
      hashCode = hashCode * 8191 + encryptType.getValue();

    return hashCode;
  }

  @Override
  public int compareTo(AccountPassword other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetId()).compareTo(other.isSetId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.id, other.id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetAccountPassword()).compareTo(other.isSetAccountPassword());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAccountPassword()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.accountPassword, other.accountPassword);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetEncryptType()).compareTo(other.isSetEncryptType());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEncryptType()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.encryptType, other.encryptType);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("AccountPassword(");
    boolean first = true;

    sb.append("id:");
    sb.append(this.id);
    first = false;
    if (!first) sb.append(", ");
    sb.append("accountPassword:");
    if (this.accountPassword == null) {
      sb.append("null");
    } else {
      sb.append(this.accountPassword);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("encryptType:");
    if (this.encryptType == null) {
      sb.append("null");
    } else {
      sb.append(this.encryptType);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class AccountPasswordStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public AccountPasswordStandardScheme getScheme() {
      return new AccountPasswordStandardScheme();
    }
  }

  private static class AccountPasswordStandardScheme extends org.apache.thrift.scheme.StandardScheme<AccountPassword> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, AccountPassword struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.id = iprot.readI64();
              struct.setIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // ACCOUNT_PASSWORD
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.accountPassword = iprot.readString();
              struct.setAccountPasswordIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // ENCRYPT_TYPE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.encryptType = me.tony.tonyirl.account.api.enums.PasswordEncryptType.findByValue(iprot.readI32());
              struct.setEncryptTypeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, AccountPassword struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(ID_FIELD_DESC);
      oprot.writeI64(struct.id);
      oprot.writeFieldEnd();
      if (struct.accountPassword != null) {
        oprot.writeFieldBegin(ACCOUNT_PASSWORD_FIELD_DESC);
        oprot.writeString(struct.accountPassword);
        oprot.writeFieldEnd();
      }
      if (struct.encryptType != null) {
        oprot.writeFieldBegin(ENCRYPT_TYPE_FIELD_DESC);
        oprot.writeI32(struct.encryptType.getValue());
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class AccountPasswordTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public AccountPasswordTupleScheme getScheme() {
      return new AccountPasswordTupleScheme();
    }
  }

  private static class AccountPasswordTupleScheme extends org.apache.thrift.scheme.TupleScheme<AccountPassword> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, AccountPassword struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetId()) {
        optionals.set(0);
      }
      if (struct.isSetAccountPassword()) {
        optionals.set(1);
      }
      if (struct.isSetEncryptType()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetId()) {
        oprot.writeI64(struct.id);
      }
      if (struct.isSetAccountPassword()) {
        oprot.writeString(struct.accountPassword);
      }
      if (struct.isSetEncryptType()) {
        oprot.writeI32(struct.encryptType.getValue());
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, AccountPassword struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.id = iprot.readI64();
        struct.setIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.accountPassword = iprot.readString();
        struct.setAccountPasswordIsSet(true);
      }
      if (incoming.get(2)) {
        struct.encryptType = me.tony.tonyirl.account.api.enums.PasswordEncryptType.findByValue(iprot.readI32());
        struct.setEncryptTypeIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

