spring:
  cloud:
    zookeeper:
      enabled: true
      discovery:
        enabled: true
        register: false
      connect-string: zk1.tony.dev:2181
logging:
  config: classpath:log4j2.xml

---

spring:
  profiles: prod
  cloud:
      zookeeper:
        connect-string: tz-bj-1:2611,tz-bj-2:2611,tz-bj-2:2612